language: node_js
before_install:
  - cd server
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run dbreset
  - echo "export const severRoute = 'http://localhost:3000';" > server/frontend/constants/routeAPI.js
node_js:
  - "0.12"